import { StyleSheet, Dimensions } from "react-native";

import { COLORS, SIZES, FONT } from "../../../constants";
import { Size } from "aws-cdk-lib";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.tertiary,
    borderRadius: 20,
    paddingBottom: 8,
    paddingTop: 16,
    marginBottom: 32,
  },
  timeContainer: {
    flexDirection: "row",
    margin: 8,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 16,
    width: "80%",
  },
  time: {
    color: COLORS.white,
    fontFamily: FONT.semi,
    fontSize: 40,
    minWidth: 180,
    textAlign: 'center'
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    flex: 1,
    shadowColor: COLORS.secondary,
    shadowOpacity: 1,
    marginHorizontal: 8,
  },
  primaryButtons: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 16,
    marginHorizontal: 8,
    alignItems: "center",
    flex: 1,
  },
  grayButtons: {
    backgroundColor: COLORS.gray,
    borderRadius: 10,
    paddingVertical: 16,
    marginHorizontal: 8,
    alignItems: "center",
    flex: 1,
  },
  buttonText: {
    textAlign: "center",
    color: COLORS.white,
    fontFamily: FONT.semi,
    fontSize: SIZES.medium,
    paddingHorizontal: 10,
  },
  dashboardButton: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    paddingVertical: 12,
    marginHorizontal: 8,
    marginTop: 16,
    alignItems: "center",
    flex: 1,
  },
  dashboardText: {
    color: COLORS.gray3,
    fontFamily: FONT.medium,
    fontSize: SIZES.small,
  },
  icon: {
    height: 40,
    width: 40,
    tintColor: COLORS.white,
    marginRight: 20,
  },
  vitalsContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginTop: 16,
    marginBottom: 8,
    backgroundColor: COLORS.gray3,
    padding: 12,
    borderRadius: 10,
    marginHorizontal: 16,
  },
  scoreContainer: {
    flex: 2,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  vitalsText: {
    fontSize: SIZES.small,
    fontFamily: FONT.regular,
    color: COLORS.white,
  },
  stressIcon: {
    width: 20,
    height: 20,
  },
  focusIcon: {
    width: 20,
    height: 20,
    transform: [{ rotate: "180deg" }],
  },
  stressModal: {
    backgroundColor: COLORS.tertiary,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    width: Dimensions.get("window").width - 32,
    marginLeft: -4,
  },
  brainIcon: {
    width: 100,
    height: 100,
  },
  stressText: {
    color: COLORS.white,
    fontFamily: FONT.semi,
    fontSize: SIZES.xLarge,
    marginVertical: 12,
    textAlign: 'center',
    lineHeight: 30,
  },
  stressSubText: {
    color: COLORS.gray2,
    fontFamily: FONT.regular,
    fontSize: SIZES.medium,
    textAlign: 'center'
  },
  earnXPText: {
    marginVertical: 12,
    color: COLORS.primary,
    fontFamily: FONT.semi,
    fontSize: SIZES.medium,
  },
  modalPrimaryButtons: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    width: '100%',
    marginTop: 8,
  },
  modalGrayButtons: {
    backgroundColor: COLORS.gray,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    width: '100%',
    marginVertical: 8,
  },
  breakTimeContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 32,
  },
  addContainer: {
    backgroundColor: COLORS.secondary,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: 'center',
    borderColor: COLORS.primary,
    borderWidth: 2,
    marginTop: 24,
    padding: 2,
  },
  addTodoText: {
    flex: 1,
    color: COLORS.white,
    fontSize: SIZES.medium,
    fontFamily: FONT.semi,
    marginLeft: 16,
  },
  todoText: {
    flex: 1,
    color: COLORS.white,
    fontSize: SIZES.medium,
    fontFamily: FONT.semi,
    marginLeft: 16,
  }, 
  logo: {
    height: 24,
    width: 24,
    marginVertical: 12,
    marginLeft: 12,
  },
  trashIcon: {
    height: 20,
    marginRight: -16,
  },
  todoContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 16,
    paddingHorizontal: 16,
    backgroundColor: COLORS.gray3,
    borderRadius: 12,
  },
  todoItemText: { 
    flex: 1, 
    textAlign: "center", 
    color: COLORS.white 
  },
  countdownContainer: {
    paddingBottom: 16,
    paddingHorizontal: 16,
    marginLeft: 36,
  },
  countdownText: {
    color: COLORS.white,
    fontFamily: FONT.semi,
    fontSize: SIZES.medium,
  },
  listContainer: { 
    flex: 1, 
    alignSelf: "stretch", 
    padding: 8 
  },
  listItemSeparator: { height: 10 },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderRadius: 4,
    borderColor: COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    // marginLeft: 15,
  },
  checkboxTick: {
    width: 12,
    height: 12,
    backgroundColor: COLORS.primary,
  },
  dateText: {
    color: COLORS.gray2,
    marginLeft: 52,
    marginBottom: 16,
    marginTop: 8,
  },
  modalContainer: {
    backgroundColor: COLORS.tertiary,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    width: Dimensions.get("window").width - 32,
  },
  modalTitle: {
    fontSize: SIZES.large,
    fontFamily: FONT.semi,
    color: COLORS.white,
    marginBottom: 24,
  },
  modalInput: {
    borderColor: COLORS.gray4,
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    marginBottom: 24,
  },
  calendarButton: {
    flex: 1.5,
    marginVertical: 8,
  },
  calendarButtonText: {
    color: COLORS.primary,
    fontWeight: "bold",
  },
  calendarContainer: {
    width: "100%",
    height: 350,
  },
  calendar: {
    borderRadius: 10,
    padding: 10,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  addTaskButton: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
    marginLeft: 8,
    flex: 1,
    alignItems: "center",
  },
  cancelButton: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: COLORS.gray,
    marginRight: 8,
    flex: 1,
    alignItems: "center",
  },
  modalButtonText: {
    color: COLORS.white,
    fontFamily: FONT.semi,
    fontSize: SIZES.medium,
  },
  modalSecondaryButtons: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 16,
    marginHorizontal: 8,
    alignItems: "center",
    marginTop: 8,
  },
});

export default styles;
